-- map("n", "q", "", { desc = "custom quick edit" })
-- map("n", "qa", "", { desc = "append" })
-- map("n", "qa`", "vi`a", { desc = "append ``" }) --
-- map("n", "qa'", "vi'a", { desc = "append ''" }) --
-- map("n", 'qa"', 'vi"a', { desc = 'append ""' }) --
-- map("n", "qa(", "vi(a", { desc = "append ()" }) --
-- map("n", "qa[", "vi[a", { desc = "append []" }) --
-- map("n", "qa{", "vi{a", { desc = "append {}" }) --
-- map("n", "qa<", "vi<a", { desc = "append <>" }) --
-- map("n", "ql", "", { desc = "append last" })
-- map("n", "ql`", "$f`i", { desc = "append last ``" })
-- map("n", "ql'", "$f'i", { desc = "append last ''" })
-- map("n", 'ql"', '$f"i', { desc = 'append last ""' })
-- map("n", "ql(", "$f)i", { desc = "append last ()" })
-- map("n", "ql[", "$f>i", { desc = "append last []" })
-- map("n", "ql{", "$f}i", { desc = "append last {}" })
-- map("n", "ql<", "$f>i", { desc = "append last <>" })
-- map("n", "qc", "", { desc = "change" })
-- map("n", "qcw", "ciw", { desc = "change word" })
-- map("n", "qct", "cit", { desc = "change in tag" })
-- map("n", "qc`", "ci`", { desc = "change in ``" })
-- map("n", "qc'", "ci'", { desc = "change in ''" })
-- map("n", 'qc"', 'ci"', { desc = 'change in ""' })
-- map("n", "qc(", "ci(", { desc = "change in ()" })
-- map("n", "qc[", "ci[", { desc = "change in []" })
-- map("n", "qc{", "ci{", { desc = "change in {}" })
-- map("n", "qc<", "ci<", { desc = "change in <>" })
-- map("n", "qi", "", { desc = "select inside" })
-- map("n", "qiw", "viw", { desc = "select word" }) --
-- map("n", "qit", "vit", { desc = "select in tag" })
-- map("n", "qif", "v$%", { desc = "select function" }) --
-- map("n", "qi`", "vi`", { desc = "select in ``" })
-- map("n", "qi'", "vi'", { desc = "select in ''" })
-- map("n", 'qi"', 'vi"', { desc = 'select in ""' })
-- map("n", "qi(", "vi(", { desc = "select in ()" })
-- map("n", "qi[", "vi[", { desc = "select in []" })
-- map("n", "qi{", "vi{", { desc = "select in {}" })
-- map("n", "qi<", "vi<", { desc = "select in <>" })
-- map("n", "qo", "", { desc = "select around" })
-- map("n", "qot", "vat", { desc = "select around tag" })
-- map("n", "qo`", "va`", { desc = "select around ``" })
-- map("n", "qo'", "va'", { desc = "select around ''" })
-- map("n", 'qo"', 'va"', { desc = 'select around ""' })
-- map("n", "qo(", "va(", { desc = "select around ()" })
-- map("n", "qo[", "va[", { desc = "select around []" })
-- map("n", "qo{", "va{", { desc = "select around {}" })
-- map("n", "qo<", "va<", { desc = "select around <>" })

map("n", "`", "vi`A", { desc = "append in ``" }) -- ok
map("n", "'", "vi'A", { desc = "append in ''" }) -- ok
map("n", '"', 'vi"A', { desc = 'append in ""' }) -- ok
map("n", "(", "vi(A", { desc = "append in ()" }) --
map("n", "[", "vi[A", { desc = "append in []" }) --
map("n", "{", "vi{A", { desc = "append in {}" }) --
map("n", "<", "vi<A", { desc = "append in <>" }) --
map("n", "~", "$F`i", { desc = "append before last ``" })
map("n", "<>", "$F>i", { desc = "append before last <>" })
map("n", "''", "$F'i", { desc = "append before last ''" })
map("n", '""', '$F"i', { desc = 'append before last ""' })
map("n", "()", "$F)i", { desc = "append before last ()" })
map("n", "[]", "$F]i", { desc = "append before last []" })
map("n", "{}", "$F}i", { desc = "append before last {}" })
map("n", "<C-w>", "ciw", { desc = "change word" })
map("n", "<C-t>", "cit", { desc = "change in tag" })
map("n", "<C-`>", "ci`", { desc = "change in ``" })
map("n", "<C-'>", "ci'", { desc = "change in ''" })
map("n", '<C-">', 'ci"', { desc = 'change in ""' })
map("n", "<C-S-'>", 'ci"', { desc = 'change in ""' })
map("n", "<C-S-9>", "ci(", { desc = "change in ()" })
map("n", "<C-[>", "ci[", { desc = "change in []" })
map("n", "<C-S-[>", "ci{", { desc = "change in {}" })
map("n", "<C-S-,>", "ci<", { desc = "change in <>" })
map("n", "<A-w>", "viw", { desc = "select word" }) -- ok
map("n", "<A-t>", "vit", { desc = "select in tag" })
map("n", "<A-f>", "V$%", { desc = "select function" }) -- ok
map("n", "<A-`>", "vi`", { desc = "select in ``" })
map("n", "<A-'>", "vi'", { desc = "select in ''" })
map("n", "<A-S-'>", 'vi"', { desc = 'select in ""' })
map("n", "<A-S-9>", "vi(", { desc = "select in ()" })
map("n", "<A-[>", "vi[", { desc = "select in []" })
map("n", "<A-S-[>", "vi{", { desc = "select in {}" })
map("n", "<A-S-,>", "vi<", { desc = "select in <>" })
map("n", "<C-A-t>", "vat", { desc = "select around tag" })
map("n", "<C-A-`>", "va`", { desc = "select around ``" })
map("n", "<C-A-'>", "va'", { desc = "select around ''" })
map("n", "<C-A-S-'>", 'va"', { desc = 'select around ""' })
map("n", "<C-A-S-9>", "va(", { desc = "select around ()" })
map("n", "<C-A-[>", "va[", { desc = "select around []" })
map("n", "<C-A-S-[>", "va{", { desc = "select around {}" })
map("n", "<C-A-S-,>", "va<", { desc = "select around <>" })
--
map("n", "<leader>h", "", { desc = "custom quick edit" })
map("n", "<leader>ha", "", { desc = "append" })
map("n", "<leader>ha`", "vi`A", { desc = "append ``" }) --
map("n", "<leader>ha'", "vi'A", { desc = "append ''" }) --
map("n", '<leader>ha"', 'vi"A', { desc = 'append ""' }) --
map("n", "<leader>ha(", "vi(A", { desc = "append ()" }) --
map("n", "<leader>ha[", "vi[A", { desc = "append []" }) --
map("n", "<leader>ha{", "vi{A", { desc = "append {}" }) --
map("n", "<leader>ha<", "vi<A", { desc = "append <>" }) --
map("n", "<leader>hl", "", { desc = "append last" })
map("n", "<leader>hl`", "$F`i", { desc = "append last ``" })
map("n", "<leader>hl'", "$F'i", { desc = "append last ''" })
map("n", '<leader>hl"', '$F"i', { desc = 'append last ""' })
map("n", "<leader>hl(", "$F)i", { desc = "append last ()" })
map("n", "<leader>hl[", "$F>i", { desc = "append last []" })
map("n", "<leader>hl{", "$F}i", { desc = "append last {}" })
map("n", "<leader>hl<", "$F>i", { desc = "append last <>" })
map("n", "<leader>hc", "", { desc = "change" })
map("n", "<leader>hcw", "ciw", { desc = "change word" })
map("n", "<leader>hct", "cit", { desc = "change in tag" })
map("n", "<leader>hc`", "ci`", { desc = "change in ``" })
map("n", "<leader>hc'", "ci'", { desc = "change in ''" })
map("n", '<leader>hc"', 'ci"', { desc = 'change in ""' })
map("n", "<leader>hc(", "ci(", { desc = "change in ()" })
map("n", "<leader>hc[", "ci[", { desc = "change in []" })
map("n", "<leader>hc{", "ci{", { desc = "change in {}" })
map("n", "<leader>hc<", "ci<", { desc = "change in <>" })
map("n", "<leader>hi", "", { desc = "select inside" })
map("n", "<leader>hiw", "viw", { desc = "select word" }) --
map("n", "<leader>hit", "vit", { desc = "select in tag" })
map("n", "<leader>hif", "V$%", { desc = "select function" }) --
map("n", "<leader>hi`", "vi`", { desc = "select in ``" })
map("n", "<leader>hi'", "vi'", { desc = "select in ''" })
map("n", '<leader>hi"', 'vi"', { desc = 'select in ""' })
map("n", "<leader>hi(", "vi(", { desc = "select in ()" })
map("n", "<leader>hi[", "vi[", { desc = "select in []" })
map("n", "<leader>hi{", "vi{", { desc = "select in {}" })
map("n", "<leader>hi<", "vi<", { desc = "select in <>" })
map("n", "<leader>ho", "", { desc = "select around" })
map("n", "<leader>hot", "vat", { desc = "select around tag" })
map("n", "<leader>ho`", "va`", { desc = "select around ``" })
map("n", "<leader>ho'", "va'", { desc = "select around ''" })
map("n", '<leader>ho"', 'va"', { desc = 'select around ""' })
map("n", "<leader>ho(", "va(", { desc = "select around ()" })
map("n", "<leader>ho[", "va[", { desc = "select around []" })
map("n", "<leader>ho{", "va{", { desc = "select around {}" })
map("n", "<leader>ho<", "va<", { desc = "select around <>" })
