#!/bin/bash

options=(
	style=round
	# width=6.0
	# hidpi=off
	# active_color=0xffe2e2e3
	inactive_color=0xff414550

	# hidpi=on
	width=20.0
	active_color="glow(0xffFFCC00)"

)

borders "${options[@]}"
